export const portfolioProjects = [
  {
    slug: 'vokabellab',
    title: 'Vokabellab',
    client: 'Vokabellab',
    brand: 'Vokabellab',
    category: 'Web app educativa',
    description: 'Plataforma de aprendizaje de vocabulario en alemán con una interfaz clara, rápida y pensada para repetir contenido útil sin fricción.',
    longDescription: 'Vokabellab es una plataforma educativa enfocada en aprendizaje práctico de vocabulario en alemán. El trabajo se centró en construir una experiencia limpia, orientada a uso recurrente, con foco en claridad visual, organización por bloques y sensación de producto ligero.',
    image: 'img/vokabellab.webp',
    ogImage: 'https://webfuengirola.com/img/vokabellab.webp',
    imageWidth: 800,
    imageHeight: 400,
    imageAlt: 'Captura de Vokabellab, plataforma para practicar vocabulario de alemán',
    ogAlt: 'Vista previa de la plataforma educativa Vokabellab',
    url: 'https://www.vokabellab.com',
    urlLabel: 'Ver web en vivo',
    tech: ['React', 'JavaScript', 'HTML', 'CSS'],
    services: ['Diseño de interfaz', 'Arquitectura de producto', 'UX educativa', 'Optimización responsive'],
    result: 'Una web app educativa preparada para crecer como producto digital, con una interfaz simple de entender y cómoda para repetir sesiones de aprendizaje.',
    seoTitle: 'Vokabellab | Caso real de web app educativa',
    seoDescription: 'Caso real de Vokabellab: diseño y desarrollo de una web app educativa para practicar vocabulario en alemán con enfoque en claridad, producto y recurrencia.',
    heroLabel: 'Caso real · Web app educativa',
    cardTags: [
      { label: 'Web app', className: 'tag--blue' },
      { label: 'Educación', className: 'tag--green' },
    ],
  },
  {
    slug: 'samuel-coach-aleman',
    title: 'Samuel Coach de Alemán',
    client: 'Samuel Coach de Alemán',
    brand: 'Samuel Coach de Alemán',
    category: 'Landing page de captación',
    description: 'Web de captación para servicios de coaching de alemán con propuesta de valor clara, estructura SEO y múltiples puntos de conversión.',
    longDescription: 'Este proyecto se construyó como una landing page comercial para un coach de alemán. La prioridad fue ordenar el mensaje, dejar muy clara la propuesta, explicar servicios sin sobrecargar la página y facilitar contacto directo desde distintos puntos del recorrido.',
    image: 'img/samuel-coach.webp',
    ogImage: 'https://webfuengirola.com/img/samuel-coach.webp',
    imageWidth: 800,
    imageHeight: 400,
    imageAlt: 'Captura de la landing page de Samuel Coach de Alemán',
    ogAlt: 'Vista previa de la web de Samuel Coach de Alemán',
    url: 'https://www.samuelcoachdealeman.com',
    urlLabel: 'Ver web en vivo',
    tech: ['HTML', 'CSS', 'JavaScript', 'SEO on-page'],
    services: ['Copy comercial', 'Landing page', 'SEO de servicios', 'Optimización de conversión'],
    result: 'Una web de captación más clara y enfocada a convertir visitas en contactos cualificados, sin dispersión ni bloques decorativos innecesarios.',
    seoTitle: 'Samuel Coach de Alemán | Caso real de landing page SEO',
    seoDescription: 'Proyecto real para Samuel Coach de Alemán: landing page de captación con estructura SEO, narrativa comercial clara y contacto directo.',
    heroLabel: 'Caso real · Landing page',
    cardTags: [
      { label: 'Landing page', className: 'tag--purple' },
      { label: 'SEO', className: 'tag--orange' },
    ],
  },
  {
    slug: 'personal-trainer-fuengirola',
    title: 'Personal Trainer Fuengirola',
    client: 'Personal Trainer Fuengirola',
    brand: 'Personal Trainer Fuengirola',
    category: 'Landing page local',
    description: 'Landing page local para un entrenador personal en Fuengirola, enfocada en servicios, confianza y contacto directo por WhatsApp.',
    longDescription: 'La web se planteó como una landing local de captación para servicios de entrenamiento personal. El objetivo fue condensar oferta, metodología y llamada a la acción en un formato sencillo, rápido de consumir y orientado a búsquedas locales.',
    image: 'img/personal-trainer.webp',
    ogImage: 'https://webfuengirola.com/img/personal-trainer.webp',
    imageWidth: 800,
    imageHeight: 400,
    imageAlt: 'Captura de la web Personal Trainer Fuengirola',
    ogAlt: 'Vista previa de la landing page de Personal Trainer Fuengirola',
    url: 'https://www.personaltrainerfuengirola.com',
    urlLabel: 'Ver web en vivo',
    tech: ['HTML', 'CSS', 'JavaScript', 'SEO local'],
    services: ['Landing local', 'Diseño responsive', 'SEO local', 'CTA por WhatsApp'],
    result: 'Una página compacta, pensada para búsquedas locales y contacto rápido, con menos fricción entre visita, confianza y acción.',
    seoTitle: 'Personal Trainer Fuengirola | Caso real de landing local',
    seoDescription: 'Caso real de Personal Trainer Fuengirola: landing page local con SEO local, estructura clara y contacto directo por WhatsApp.',
    heroLabel: 'Caso real · Captación local',
    cardTags: [
      { label: 'Landing page', className: 'tag--purple' },
      { label: 'Deporte', className: 'tag--red' },
      { label: 'SEO local', className: 'tag--orange' },
    ],
  },
  {
    slug: 'im-kontext-vokabellab',
    title: 'Im Kontext — Vokabellab',
    client: 'Vokabellab',
    brand: 'Im Kontext',
    category: 'Micro web app educativa',
    description: 'Herramienta para aprender alemán en contexto, usando frases reales y una interfaz ligera pensada para foco y continuidad.',
    longDescription: 'Im Kontext es una herramienta derivada del ecosistema Vokabellab, pensada para estudiar vocabulario dentro de frases reales. La ejecución se apoyó en una interfaz sobria, navegación simple y una experiencia de producto centrada en lectura, comprensión y repetición.',
    image: 'img/imkontext.webp',
    ogImage: 'https://webfuengirola.com/img/imkontext.webp',
    imageWidth: 800,
    imageHeight: 400,
    imageAlt: 'Captura de la herramienta educativa Im Kontext',
    ogAlt: 'Vista previa de la app Im Kontext de Vokabellab',
    url: 'https://imkontext.vokabellab.com',
    urlLabel: 'Ver web en vivo',
    tech: ['React', 'JavaScript', 'HTML', 'CSS'],
    services: ['Diseño UX', 'Producto educativo', 'Interfaz ligera', 'Optimización responsive'],
    result: 'Una micro app educativa enfocada en una sola tarea bien resuelta: practicar alemán en contexto con una experiencia limpia y utilizable.',
    seoTitle: 'Im Kontext | Caso real de herramienta educativa en alemán',
    seoDescription: 'Caso real de Im Kontext: herramienta educativa para aprender alemán en contexto con frases reales y una experiencia de producto clara.',
    heroLabel: 'Caso real · Micro app educativa',
    cardTags: [
      { label: 'Web app', className: 'tag--blue' },
      { label: 'Educación', className: 'tag--green' },
    ],
  },
  {
    slug: 'der-die-das-vokabellab',
    title: 'Der Die Das — Vokabellab',
    client: 'Vokabellab',
    brand: 'Der Die Das',
    category: 'Microproducto educativo',
    description: 'Herramienta específica para practicar artículos en alemán con una experiencia rápida, visual y fácil de repetir.',
    longDescription: 'Der Die Das se planteó como un microproducto dentro de una familia educativa más amplia. La prioridad fue velocidad de uso, una interfaz muy directa y una experiencia casi de repetición instantánea, ideal para sesiones cortas y frecuentes.',
    image: 'img/derdiedas-vokabellab.webp',
    ogImage: 'https://webfuengirola.com/img/derdiedas-vokabellab.webp',
    imageWidth: 1600,
    imageHeight: 900,
    imageAlt: 'Captura de Der Die Das, herramienta para practicar artículos en alemán',
    ogAlt: 'Vista previa de Der Die Das de Vokabellab',
    url: 'https://derdiedas.vokabellab.com',
    urlLabel: 'Ver web en vivo',
    tech: ['React', 'JavaScript', 'HTML', 'CSS'],
    services: ['Microproducto digital', 'Diseño de interfaz', 'UX educativa', 'Responsive'],
    result: 'Un producto muy enfocado, rápido de entender y listo para usarse como pieza concreta dentro de una estrategia educativa mayor.',
    seoTitle: 'Der Die Das | Caso real de microproducto educativo',
    seoDescription: 'Proyecto real de Der Die Das: micro herramienta educativa para practicar artículos en alemán con una interfaz directa y visual.',
    heroLabel: 'Caso real · Microproducto',
    cardTags: [
      { label: 'Web app', className: 'tag--blue' },
      { label: 'Educación', className: 'tag--green' },
      { label: 'Microproducto', className: 'tag--orange' },
    ],
  },
  {
    slug: 'sport-massage-fuengirola',
    title: 'Sport Massage Fuengirola',
    client: 'Sport Massage Fuengirola',
    brand: 'Sport Massage Fuengirola',
    category: 'Landing page local',
    description: 'Landing local enfocada en explicar servicios, transmitir confianza y convertir visitas en contactos para reserva.',
    longDescription: 'Este proyecto se diseñó como una web local de captación para servicios de masaje deportivo. El trabajo combinó claridad en oferta, estructura orientada a confianza y una narrativa enfocada a facilitar reserva o consulta directa.',
    image: 'img/sport-massage-fuengirola.webp',
    ogImage: 'https://webfuengirola.com/img/sport-massage-fuengirola.webp',
    imageWidth: 1600,
    imageHeight: 900,
    imageAlt: 'Captura de la landing page Sport Massage Fuengirola',
    ogAlt: 'Vista previa de Sport Massage Fuengirola',
    url: 'https://www.sportmassagefuengirola.com',
    urlLabel: 'Ver web en vivo',
    tech: ['HTML', 'CSS', 'JavaScript', 'SEO local'],
    services: ['Landing local', 'Diseño comercial', 'Optimización responsive', 'SEO local'],
    result: 'Una presencia digital orientada a negocio local, pensada para convertir búsquedas en contactos reales con un mensaje más nítido.',
    seoTitle: 'Sport Massage Fuengirola | Caso real de landing local',
    seoDescription: 'Caso real de Sport Massage Fuengirola: landing de captación local con foco en confianza, servicios y conversión a contacto.',
    heroLabel: 'Caso real · Salud y captación local',
    cardTags: [
      { label: 'Landing page', className: 'tag--purple' },
      { label: 'Salud', className: 'tag--green' },
      { label: 'SEO local', className: 'tag--orange' },
    ],
  },
  {
    slug: 'agama',
    title: 'Agama',
    client: 'Agama Pigmentos & Masterbatch',
    brand: 'Agama',
    category: 'Web corporativa',
    description: 'Web corporativa de producto para pigmentos, masterbatch y aditivos, con foco en presentación comercial y claridad de catálogo.',
    longDescription: 'Agama necesitaba una web corporativa sobria y comercial para presentar líneas de producto industriales de forma clara. La solución se centró en jerarquía visual, estructura limpia y una lectura más accesible para visitante técnico o comprador.',
    image: 'img/agama.webp',
    ogImage: 'https://webfuengirola.com/img/agama.webp',
    imageWidth: 800,
    imageHeight: 800,
    imageAlt: 'Portada del proyecto web corporativo Agama',
    ogAlt: 'Vista previa del proyecto Agama',
    url: 'https://www.agama.com.mx',
    urlLabel: 'Ver web en vivo',
    tech: ['HTML', 'CSS', 'JavaScript', 'Arquitectura de contenidos'],
    services: ['Web corporativa', 'Estructura de catálogo', 'Diseño comercial', 'Responsive'],
    result: 'Una web corporativa más clara para presentar catálogo, transmitir solidez y facilitar que el producto se entienda mejor comercialmente.',
    seoTitle: 'Agama | Caso real de web corporativa industrial',
    seoDescription: 'Proyecto real de Agama: web corporativa industrial para presentar pigmentos, masterbatch y aditivos con estructura clara y comercial.',
    heroLabel: 'Caso real · Web corporativa',
    cardTags: [
      { label: 'Web corporativa', className: 'tag--red' },
      { label: 'Industria', className: 'tag--orange' },
    ],
  },
  {
    slug: 'fisioapp-panel-clinica',
    title: 'FisioApp — Panel de clínica',
    client: 'FisioApp demo comercial',
    brand: 'FisioApp',
    category: 'Web app / SaaS',
    description: 'Panel de gestión clínica para fisioterapia con pacientes, sesiones, facturación y documentos en una interfaz pensada para trabajo diario.',
    longDescription: 'FisioApp es una web app de gestión clínica pensada para centralizar operativa real: directorio de pacientes, sesiones, facturación y generación de documentos desde un panel claro y rápido de usar. La demo pública enseña el producto sin tocar el entorno real, pero la propuesta comercial está enfocada a resolver trabajo interno de clínica, no solo a enseñar pantallas.',
    image: 'img/clinica-demo-v2.webp',
    ogImage: 'https://webfuengirola.com/img/clinica-demo-v2.webp',
    imageWidth: 1600,
    imageHeight: 900,
    imageAlt: 'Captura del panel administrador de FisioApp',
    ogAlt: 'Vista previa del panel de FisioApp',
    url: 'https://webfuengirola.com/portfolio/demo.html',
    urlLabel: 'Probar demo',
    tech: ['Node.js', 'Express', 'React', 'Render'],
    services: ['Panel administrativo', 'Gestión de pacientes', 'Facturación clínica', 'Separación demo / producción'],
    result: 'Una demo comercial que deja ver un producto utilitario y serio, orientado a mejorar la gestión diaria de una clínica sin mezclar entorno público y entorno real.',
    seoTitle: 'FisioApp | Caso real de panel SaaS para clínica',
    seoDescription: 'Caso real de FisioApp: panel SaaS para clínica con pacientes, sesiones, facturación y documentos en una experiencia de gestión clara y comercial.',
    heroLabel: 'Caso real · SaaS / producto digital',
    cardTags: [
      { label: 'Web app', className: 'tag--blue' },
      { label: 'SaaS', className: 'tag--purple' },
      { label: 'Salud', className: 'tag--green' },
    ],
  },
];
